fix: Test changelug update

diff --git a/.github/workflows/helm-chart-release.yaml b/.github/workflows/helm-chart-release.yaml
--- a/.github/workflows/helm-chart-release.yaml
+++ b/.github/workflows/helm-chart-release.yaml
@@ -9,32 +9,32 @@ jobs:
       contents: write
     runs-on: ubuntu-latest
     steps:
-      - name: Wait for container images build
-        run: |
-          while :; do
-            result=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-              https://api.github.com/repos/${{ github.repository }}/actions/runs | \
-              jq -r '.workflow_runs | map(select(.name == "Release container images")) | sort_by(.created_at) | reverse | .[0]')
-            status=$(echo "$result" | jq -r '.status')
-            conclusion=$(echo "$result" | jq -r '.conclusion')
-            if [[ "$status" == "completed" ]]; then
-              if [[ "$conclusion" == "success" ]]; then
-                echo "Release container images workflow completed successfully"
-                break
-              else
-                echo "Release container images workflow failed"
-                exit 1
-              fi
-            elif [[ "$status" == "in_progress" ]]; then
-              echo "Release container images workflow is still running"
-              sleep 60
-            else
-              echo "Release container images workflow returned unexpected status: $status"
-              exit 1
-            fi
-          done
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Wait for container images build
+      #   run: |
+      #     while :; do
+      #       result=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+      #         https://api.github.com/repos/${{ github.repository }}/actions/runs | \
+      #         jq -r '.workflow_runs | map(select(.name == "Release container images")) | sort_by(.created_at) | reverse | .[0]')
+      #       status=$(echo "$result" | jq -r '.status')
+      #       conclusion=$(echo "$result" | jq -r '.conclusion')
+      #       if [[ "$status" == "completed" ]]; then
+      #         if [[ "$conclusion" == "success" ]]; then
+      #           echo "Release container images workflow completed successfully"
+      #           break
+      #         else
+      #           echo "Release container images workflow failed"
+      #           exit 1
+      #         fi
+      #       elif [[ "$status" == "in_progress" ]]; then
+      #         echo "Release container images workflow is still running"
+      #         sleep 60
+      #       else
+      #         echo "Release container images workflow returned unexpected status: $status"
+      #         exit 1
+      #       fi
+      #     done
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Checkout
         uses: actions/checkout@v4
@@ -76,3 +76,30 @@ jobs:
           charts_dir: helm
           config: .github/configs/cr.yaml
           skip_existing: true
+      
+      - name: Update main changelog
+        if: steps.semantic-release.outputs.new_release_published == 'true'
+        run: |
+          releases=$(gh release list --limit 2 --json name)
+          latest_release_tag=$(echo "$releases" | jq -r '.[0].name')
+          previous_release_tag=$(echo "$releases" | jq -r '.[1].name')
+          clean_latest_version=$(echo $latest_release_tag | sed -E 's/v//g')
+          echo "#### ${clean_latest_version}: Release" >> CHANGELOG.new
+          echo >> CHANGELOG.new
+          for logEntry in $(git log --first-parent --merges --abbrev-commit --pretty=oneline $previous_release_tag..$latest_release_tag| sed -E 's/^.*#//g;s/ from.*//g;/Merge branch/d;s/[^0-9]*//g')
+          do
+            echo " - "$(gh pr view $logEntry --json title,number,author -t "{{.title}} (#{{.number}}) @{{.author.login}}") >> CHANGELOG.new
+          done
+          echo >> CHANGELOG.new
+          if [ -e CHANGELOG.md ]
+          then
+            cat CHANGELOG.md >> CHANGELOG.new
+          fi
+          mv CHANGELOG.new CHANGELOG.md
+          git config --global user.name "GitHub Actions Bot"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git add CHANGELOG.md
+          git commit -m "Update CHANGELOG for $clean_latest_version [no ci]"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  
